server:
  port: 16666
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        #配置后端服务的路由规则
        - uri: lb://web-back
          predicates:
            - Path=/back/**
          filters:
            #配置一个自带的过滤器，该过滤器的作用表示会过滤掉请求的第一层路径
            - StripPrefix=1
        #配置搜索服务的路由规则
        - uri: lb://web-search
          predicates:
            - Path=/search/**
        #配置商品详情服务的路由规则
        - uri: lb://web-item
          predicates:
            - Path=/item/**,/html/**
        #配置sso服务的路由规则
        - uri: lb://web-sso
          predicates:
            - Path=/sso/**
        #配置购物车服务的路由规则
        - uri: lb://web-cart
          predicates:
            - Path=/cart/**
        #配置订单服务的路由规则
        - uri: lb://web-order
          predicates:
            - Path=/order/**,/pay/**
        #配置前台服务的路由规则
        - uri: lb://web-front
          predicates:
            - Path=/**
